const dialog=document.querySelector('#window'),body=document.querySelector('#window-body');
let lang=document.documentElement.lang==='en'?'en':'ru',sound=false,audio,active=null,photoIndex=0,lastTrigger;
const t=(ru,en)=>lang==='ru'?ru:en;
const photos=[['work-01','Работа на рольставне: портрет девушки с неоновыми волосами','Roller shutter piece: portrait of a woman with neon hair'],['work-02','Жёлтый тег TORB поверх чёрно-белого портрета','Yellow TORB tag over a black-and-white portrait'],['work-03','Объёмный красный кусок в заброшенном цеху','Red 3D piece in an abandoned factory hall'],['work-04','Портрет художника с баллоном на красной стене','Portrait of an artist with a spray can on a red wall'],['work-05','«TORB WAS HERE»: кот с уткой на голове','“TORB WAS HERE”: a cat with a duck on its head'],['work-06','Утки-диджеи на фоне букв TORB','Duck DJs in front of TORB letters'],['work-07','Утка в маске и капюшоне рядом с цветным куском','A hooded masked duck next to a colorful piece']];
const labels={works:'WORKS',district:'TORB DISTRICT',workshops:'WORKSHOPS',fight:'SPRAYFIGHT',about:'ABOUT',contact:'CONTACT'};
function tone(){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='square';o.frequency.setValueAtTime(380,audio.currentTime);o.frequency.exponentialRampToValueAtTime(160,audio.currentTime+.07);g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.09);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.1)}catch{sound=false;document.querySelector('#sound').textContent='SOUND OFF';document.querySelector('#sound').setAttribute('aria-pressed','false')}}
function title(k,title){return `<p class="kicker">${k}</p><h2 id="window-title">${title}</h2>`}
const form=()=>`<form class="contact-form" data-contact-form data-endpoint="https://api.torb.website:8443/api/contact" data-sending-text="${t('Отправка…','Sending…')}" data-required-text="${t('Заполните все поля','Fill in all fields')}" data-success-text="${t('Сообщение отправлено. Я скоро отвечу.','Message sent. I will reply soon.')}" data-error-text="${t('Не удалось отправить. Напишите в Telegram или Instagram.','Could not send. Message me on Telegram or Instagram.')}">
<input type="text" name="name" placeholder="${t('Ваше имя','Your name')}" autocomplete="name" required>
<input type="email" name="email" placeholder="${t('Ваш Email','Your email')}" autocomplete="email" required>
<textarea name="message" rows="5" placeholder="${t('Ваше сообщение','Your message')}" required></textarea>
<button type="submit">${t('ОТПРАВИТЬ','SEND')}</button>
<p class="form-status" data-form-status role="status" aria-live="polite"></p>
</form>`;
const internal=(url,text)=>`<a class="action" href="${url}">${text} \u2192</a>`;
const link=(url,text)=>`<a class="action" href="${url}" target="_blank" rel="noopener noreferrer">${text} ↗</a>`;
function render(){
 document.querySelector('#window-path').textContent='TORB / '+labels[active];
 if(active==='works'){
 body.innerHTML=title('01 / SELECTED WORKS',t('Следы на стенах.','Marks on walls.'))+`<div class="gallery-main"><img id="gallery-image" src="${photos[photoIndex][0]}.webp" alt="${photos[photoIndex][lang==='ru'?1:2]}"></div><div class="gallery-controls"><button id="prev" aria-label="${t('Предыдущее фото','Previous photo')}">← ${t('НАЗАД','PREV')}</button><span id="photo-caption"></span><button id="next" aria-label="${t('Следующее фото','Next photo')}">${t('ДАЛЬШЕ','NEXT')} →</button></div><div class="thumbnails">${photos.map((p,i)=>`<button data-photo="${i}" aria-label="${t('Фото','Photo')} ${i+1}" aria-pressed="${i===photoIndex}"><img src="${p[0]}-thumb.webp" alt="" loading="lazy"></button>`).join('')}</div>`;
 document.querySelector('#prev').onclick=()=>changePhoto(-1);document.querySelector('#next').onclick=()=>changePhoto(1);body.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>{photoIndex=Number(b.dataset.photo);updatePhoto();tone()});updatePhoto();
 }else if(active==='district'){
 body.innerHTML=title('02 / OPEN-AIR GALLERY','Torb District')+`<div class="split"><img class="feature-image" src="torb-district1.webp" alt="Граффити Torb District"><div><p>${t('Всё началось с одной работы. Со временем обычная улица превратилась в галерею под открытым небом.','It started with a single piece. Over time, an ordinary street became an open-air gallery.')}</p><p>${t('Главные герои — утки. Местные называют это «Утиные истории». Стены меняются: новые буквы, новые лица, новые истории.','The main characters are ducks. Locals call it “Duck Stories.” The walls keep changing: new letters, new faces, new stories.')}</p>${internal('torb-district'+(lang==='ru'?'-ru':'')+'.html',t('ВСЯ ИСТОРИЯ','THE FULL STORY'))}</div></div><img class="feature-image" src="torb-district2.webp" alt="Работы в Torb District" loading="lazy" style="margin-top:24px;max-height:none">`;
 }else if(active==='workshops'){
 body.innerHTML=title('03 / GET YOUR HANDS DIRTY',t('От скетча до стены.','From sketch to wall.'))+`<div class="split"><img class="feature-image" src="masterclass1.webp" alt="Мастер-класс по граффити"><div><p>${t('История граффити, работа с буквами и практика с баллончиком. Учимся управлять краской, строить композицию и находить свой стиль.','Graffiti history, letterforms and hands-on spray-paint practice. Learn to control the can, build a composition and find your own style.')}</p><div class="tags"><span>${t('Индивидуально','One-to-one')}</span><span>${t('Группы','Groups')}</span><span>${t('Фестивали','Festivals')}</span></div><p>${t('Для записи напиши город, дату и желаемый формат.','To book, send your city, date and preferred format.')}</p>${internal('workshops'+(lang==='ru'?'-ru':'')+'.html',t('ПРОГРАММА И ЗАПИСЬ','PROGRAM & BOOKING'))}${link('https://t.me/trbkwsk',t('НАПИСАТЬ В TELEGRAM','MESSAGE ON TELEGRAM'))}</div></div>`;
 }else if(active==='fight'){
 body.innerHTML=title('04 / THE GRAFFITI BATTLE SYSTEM','SPRAYFIGHT')+`<p>${t('16 художников. На вылет. Каждый раунд — новое слово, меньше времени на сомнения и больше стиля.','16 artists. Knockout rounds. A new word every round. Less time to hesitate. More style.')}</p><div class="rounds"><div class="round"><small>TOP 16</small><strong>0:30</strong><span>${t('Тег · случайное слово','Tag · random word')}</span></div><div class="round"><small>TOP 8</small><strong>1:00</strong><span>${t('Throw-up · 1 цвет','Throw-up · 1 color')}</span></div><div class="round"><small>TOP 4</small><strong>1:30</strong><span>${t('Сложная форма · 2 цвета','Complex form · 2 colors')}</span></div><div class="round"><small>FINAL</small><strong>3:00</strong><span>${t('До 4 цветов · свобода','Up to 4 colors · freedom')}</span></div></div><p>${t('Структура букв, динамика, уверенность и оригинальность. Зрители видят, как работа появляется прямо перед ними.','Letter structure, dynamics, confidence and originality. The audience watches the piece come to life in real time.')}</p>${internal('sprayfight'+(lang==='ru'?'-ru':'')+'.html',t('ПРАВИЛА И ФОРМАТ','RULES & FORMAT'))}`;
 }else if(active==='about'){
 body.innerHTML=title('05 / BEHIND THE NAME','TRBKWSK<br>AKA TORB')+`<div class="about-lead"><img class="about-photo" src="festival5.jpg" alt="${t('TORB за работой','TORB at work')}"><p>${t('Рисую граффити, работаю с буквами и рассказываю истории через изображение. TRBKWSK — имя, которым я пишу; TORB — то, как его читают на стенах.','I create graffiti focused on letterforms and visual storytelling. TRBKWSK is the name I write with; TORB is how it reads on the walls.')}</p></div>
<h3>${t('Путь','The path')}</h3>
<p>${t('Всё началось с одной работы. Со временем обычная улица в центре города превратилась в открытую галерею — Torb District. Здесь нет шаблонов: каждый рисунок становится частью живого потока, а стены меняются с каждым сезоном.','It all started with a single piece. Over time an ordinary street in the city centre turned into an open-air gallery — Torb District. There is no fixed template here: every work becomes part of a living flow, and the walls change with every season.')}</p>
<h3>${t('Практика','Practice')}</h3>
<p>${t('Расписываю стены, создаю арт-пространства, провожу мастер-классы, фестивали и джемы. Участвую в международных проектах — от городских стен до образовательных площадок.','I paint walls, build art spaces and run workshops, festivals and jams. I take part in international projects — from city walls to educational platforms.')}</p>
<p>${t('В мастер-классах соединяю историю культуры, теорию шрифта и практику с баллончиком: от первых эскизов до готовой работы на стене.','In the workshops I combine the history of the culture, letterform theory and hands-on spray practice: from the first sketches to a finished piece on the wall.')}</p>
<h3>${t('Баттлы','Battles')}</h3>
<p>${t('На протяжении пяти лет провожу граффити-баттлы. Из этого выросла система SprayFight — 16 художников, короткие раунды и понятные правила, в которых процесс создания работы виден зрителю целиком.','For five years I have been organising graffiti battles. That is where the SprayFight system came from — 16 artists, short rounds and clear rules, where the audience sees the whole piece come to life.')}</p>
<h3>${t('Принцип','What it is for')}</h3>
<p>${t('Моя цель — передать опыт, вдохновить и показать, что граффити — это живая форма искусства, объединяющая свободу, эстетику и движение.','My goal is to share experience, inspire, and show that graffiti is a living art form — combining freedom, aesthetics, and movement.')}</p>
<div class="about-sign">TORB.</div>`;
  }else{
 body.innerHTML=title('06 / LET’S MAKE SOMETHING',t('Есть идея?','Got an idea?'))+`<p>${t('Стена, мастер-класс, фестиваль или совместный проект — расскажи, что задумал.','A wall, a workshop, a festival or a collaboration — tell me what you have in mind.')}</p>${form()}<div class="contact-links"><a href="https://t.me/trbkwsk" target="_blank" rel="noopener noreferrer">Telegram <span>↗</span></a><a href="https://www.instagram.com/trbkwsk/" target="_blank" rel="noopener noreferrer">Instagram <span>↗</span></a><a href="https://youtube.com/@trbkwsk" target="_blank" rel="noopener noreferrer">YouTube <span>↗</span></a><a href="https://streeet.art/@trbkwsk" target="_blank" rel="noopener noreferrer">STREEET.ART <span>↗</span></a></div>`;
 window.TorbContact?.bind(body);
 }
 body.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{const note=document.createElement('p');note.className='image-error';note.textContent=t('Не удалось загрузить фото.','Could not load the photo.');img.replaceWith(note)},{once:true}));
}
function updatePhoto(){const p=photos[photoIndex],img=document.querySelector('#gallery-image');if(img){img.src=p[0]+'.webp';img.alt=p[lang==='ru'?1:2]}document.querySelector('#photo-caption').textContent=`${String(photoIndex+1).padStart(2,'0')} / ${String(photos.length).padStart(2,'0')} — ${p[lang==='ru'?1:2]}`;body.querySelectorAll('[data-photo]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.photo)===photoIndex)))}
function changePhoto(d){photoIndex=(photoIndex+d+photos.length)%photos.length;updatePhoto();tone()}
function openSection(section,trigger){active=section;lastTrigger=trigger;render();dialog.showModal();document.body.style.overflow='hidden';body.scrollTop=0;tone();document.querySelector('#close').focus()}
document.querySelectorAll('[data-section]').forEach(b=>b.addEventListener('click',()=>openSection(b.dataset.section,b)));
document.querySelector('#close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{document.body.style.overflow='';active=null;lastTrigger?.focus();tone()});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
document.querySelector('#sound').onclick=e=>{sound=!sound;e.currentTarget.textContent=sound?'SOUND ON':'SOUND OFF';e.currentTarget.setAttribute('aria-pressed',String(sound));e.currentTarget.setAttribute('aria-label',t(sound?'Выключить звук':'Включить звук',sound?'Mute sound':'Enable sound'));tone()};
document.querySelector('#language').onclick=()=>{lang=lang==='ru'?'en':'ru';applyLang();history.replaceState(null,'',lang==='ru'?'index-ru.html':'index.html');tone()};
document.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey)return;if(dialog.open){if(active==='works'&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();changePhoto(e.key==='ArrowLeft'?-1:1)}return}const keys=['works','district','workshops','fight','about','contact'];if(/^[1-6]$/.test(e.key)){e.preventDefault();const section=keys[Number(e.key)-1];openSection(section,document.querySelector(`[data-section="${section}"]`))}});
document.querySelector('#year').textContent=new Date().getFullYear();
function applyLang(){document.documentElement.lang=lang;document.querySelectorAll('[data-ru]').forEach(el=>el.textContent=el.dataset[lang]);const b=document.querySelector('#language');b.textContent=lang==='ru'?'EN':'RU';b.setAttribute('aria-label',lang==='ru'?'Switch to English':'Переключить на русский');document.querySelector('#close').setAttribute('aria-label',t('Закрыть окно','Close window'));if(active)render()}
applyLang();
